# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_lightgallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightgalleryimage',
            old_name='slider',
            new_name='gallery',
        ),
    ]
